# Generated by Django 2.2.3 on 2019-07-11 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190711_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.AddField(
            model_name='list',
            name='article',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='home.Article'),
        ),
        migrations.AddField(
            model_name='user',
            name='articles',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='home.Article'),
        ),
        migrations.AddField(
            model_name='user',
            name='list',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='home.List'),
        ),
    ]
