# Generated by Django 2.2.3 on 2019-07-11 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190711_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.List'),
        ),
    ]
