# Generated by Django 2.2.3 on 2019-07-11 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190711_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='article',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='home.Article'),
        ),
        migrations.AddField(
            model_name='user',
            name='articles',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='home.Article'),
        ),
    ]
