# Generated by Django 2.2.3 on 2019-07-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190711_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='articles',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='articles',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.List'),
            preserve_default=False,
        ),
    ]
