# Generated by Django 2.2.3 on 2019-07-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190712_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='list',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
