# Generated by Django 2.2.3 on 2019-07-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20190713_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editor',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
